-- MySQL Script generated by MySQL Workbench
-- Wed May 26 23:15:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TEST` ;

-- -----------------------------------------------------
-- Schema TEST
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TEST` DEFAULT CHARACTER SET utf8 ;
USE `TEST` ;

-- -----------------------------------------------------
-- Table `TEST`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`tasks` ;

CREATE TABLE IF NOT EXISTS `TEST`.`tasks` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `due_date` DATE NULL DEFAULT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `TEST`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`users` ;

CREATE TABLE IF NOT EXISTS `TEST`.`users` (
  `full_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `center_code` VARCHAR(45) NOT NULL,
  `attempts` INT(11) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`email`, `center_code`),
  CONSTRAINT `fk_INTERNAL_USER_CENTER1`
    FOREIGN KEY (`center_code`)
    REFERENCES `TEST`.`centers` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TEST`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`roles` ;

CREATE TABLE IF NOT EXISTS `TEST`.`roles` (
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  UNIQUE INDEX `CODE_UNIQUE` (`code` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `TEST`.`permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TEST`.`permissions` ;

CREATE TABLE IF NOT EXISTS `TEST`.`permissions` (
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `CODE_UNIQUE` (`code` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

